name: Deploy
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build --prod
            - name: deploy to firebase hosting
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
